# Generated by Django 5.2.5 on 2025-09-27 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(blank=True, max_length=100, null=True)),
                ('run', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('fono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idclientes', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('NumeroVenta', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Detalle venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idLote', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.CharField(blank=True, max_length=300, null=True)),
                ('tiempo_preparacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proteinas', models.CharField(blank=True, max_length=45, null=True)),
                ('azucar', models.CharField(blank=True, max_length=45, null=True)),
                ('gluten', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Nutricional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('caducidad', models.DateField()),
                ('elaboracion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('modificado', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.IntegerField(primary_key=True, serialize=False)),
                ('EstadoPedido', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
