# Generated by Django 5.2.5 on 2025-09-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_organization_zone_alter_zone_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='zone',
        ),
        migrations.AlterField(
            model_name='zone',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='dispositivos.organization'),
            preserve_default=False,
        ),
    ]
