# Generated by Django 5.2.5 on 2025-10-03 11:28

from django.db import migrations

def crear_roles_iniciales(apps, schema_editor):
    """
    Esta función crea los roles iniciales (Admin, Cliente, Usuario) en la base de datos.
    """
    Rol = apps.get_model('dispositivos', 'Rol')

    roles = [
        {'nombre': 'Admin', 'descripcion': 'Rol con permisos de administrador.'},
        {'nombre': 'Cliente', 'descripcion': 'Rol para clientes que compran en la tienda.'},
        {'nombre': 'Usuario', 'descripcion': 'Rol para usuarios generales del sistema.'}
    ]
    for rol_data in roles:
        Rol.objects.get_or_create(nombre=rol_data['nombre'], defaults={'descripcion': rol_data['descripcion']})

class Migration(migrations.Migration):

    dependencies = [
        # Esta migración depende de la anterior, donde se creó el modelo Rol.
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        # Aquí le decimos a Django que ejecute nuestra función para crear los roles.
        migrations.RunPython(crear_roles_iniciales),
    ]