# Generated by Django 5.2.5 on 2025-10-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_notificacion'),
        ('dispositivos', '0004_crear_roles_iniciales'),
    ]

    operations = [
    ]
