# Generated by Django 5.2.5 on 2025-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_remove_organization_zone_alter_zone_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dispositivos/'),
        ),
    ]
