# Generated by Django 5.2.5 on 2025-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_merge_0003_notificacion_0004_crear_roles_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('Enviado', 'Enviado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
