# Generated by Django 5.2.5 on 2025-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
