# Generated by Django 5.2.5 on 2025-11-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_direccion_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='depto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='Direccion',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='Roles',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
