# Generated by Django 5.2.5 on 2025-11-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_direccion_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True, 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='usuarios.direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='usuarios.rol'),
        ),
    ]
