# Generated by Django 5.2.5 on 2025-11-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_rol_options_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.rol'),
        ),
    ]
