# Generated by Django 5.2.5 on 2025-11-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idclientes', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('Enviado', 'Enviado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.IntegerField(db_column='idventa', primary_key=True, serialize=False)),
                ('EstadoPedido', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idLote', models.IntegerField(primary_key=True, serialize=False)),
                ('Productos', models.ForeignKey(db_column='Productos_id', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.producto')),
            ],
            options={
                'db_table': 'Lote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lote_Productos_id', models.IntegerField()),
                ('Lote_idLote', models.ForeignKey(db_column='Lote_idLote', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.lote')),
            ],
            options={
                'db_table': 'Detalle venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
