# Generated by Django 5.2.5 on 2025-11-04 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Usuarios',
            field=models.ForeignKey(db_column='Usuarios_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='clientes_idclientes',
            field=models.ForeignKey(db_column='clientes_idclientes', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.cliente'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta_idventa',
            field=models.ForeignKey(db_column='venta_idventa', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.venta'),
        ),
    ]
