# Generated by Django 5.2.5 on 2025-11-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.CharField(blank=True, max_length=300, null=True)),
                ('tiempo_preparacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proteinas', models.CharField(blank=True, max_length=45, null=True)),
                ('azucar', models.CharField(blank=True, max_length=45, null=True)),
                ('gluten', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Nutricional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReglaAlertaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_anticipacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('caducidad', models.DateField()),
                ('elaboracion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('modificado', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.DateTimeField(blank=True, null=True)),
                ('Categorias', models.ForeignKey(db_column='Categorias_id', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.categoria')),
                ('Nutricional', models.ForeignKey(db_column='Nutricional_id', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.nutricional')),
            ],
            options={
                'db_table': 'Productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductoReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.reglaalertavencimiento')),
            ],
            options={
                'unique_together': {('producto', 'regla')},
            },
        ),
    ]
