# Generated by Django 5.2.5 on 2025-11-13 22:56

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, null=True, validators=[catalogo.models.no_negativo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(blank=True, null=True, validators=[catalogo.models.no_negativo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True, validators=[catalogo.models.no_negativo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(blank=True, null=True, validators=[catalogo.models.no_negativo]),
        ),
        migrations.AlterField(
            model_name='reglaalertavencimiento',
            name='dias_anticipacion',
            field=models.IntegerField(validators=[catalogo.models.no_negativo]),
        ),
    ]
