"""
Django settings for monitoreo project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Importación necesaria para configurar los tags de mensajes
from django.contrib.messages import constants as msg

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")  # Carga el .env

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-unsafe")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
# Forzamos DEBUG a True para el entorno de desarrollo
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

# ----------------------------------------------------------------------
# --- INSTALLED_APPS CORREGIDO ---
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- TUS NUEVAS APPS ---
    # Es mejor usar la ruta completa de AppConfig para evitar conflictos
    'core.apps.CoreConfig',
    'usuarios.apps.UsuariosConfig',
    'catalogo.apps.CatalogoConfig',
    'pedidos.apps.PedidosConfig',
    
    # --- ¡NUEVA APP AÑADIDA! ---
    'proveedores.apps.ProveedoresConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monitoreo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Apunta a la carpeta 'templates' en la raíz del proyecto (para base.html)
        'DIRS': [BASE_DIR.parent / 'templates'],
        'APP_DIRS': True, # Esto permite que Django encuentre templates dentro de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monitoreo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# monitoreo/monitoreo/settings.py

# monitoreo/monitoreo/settings.py

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "forneria"),       # <-- Añadido fallback
        "USER": os.getenv("DB_USER", "root"),           # <-- ¡CRÍTICO! Añadido fallback
        "PASSWORD": os.getenv("DB_PASSWORD", ""),  # <-- ¡CRÍTICO! Añadido fallback
        "HOST": os.getenv("DB_HOST", "localhost"),      # <-- Añadido fallback
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------------------------
# Configuraciones para Archivos Multimedia/Imágenes
# ----------------------------------------------------------------------

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ----------------------------------------------------------------------
# --- Configuraciones de Autenticación CORREGIDAS ---
# ----------------------------------------------------------------------
# --- AUTH_USER_MODEL CORREGIDO ---
AUTH_USER_MODEL = 'usuarios.Usuario' # Ahora apunta a la app 'usuarios'

# --- URLs CORREGIDAS ---
# Usamos los nombres de las rutas (namespaces) para más seguridad
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'usuarios:login'
LOGIN_URL = 'usuarios:login'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ----------------------------------------------------------------------
# Configuraciones de Mensajes (message framework)
# ----------------------------------------------------------------------
MESSAGE_TAGS = {
    msg.DEBUG: 'secondary',
    msg.INFO: 'info',
    msg.SUCCESS: 'success',
    msg.WARNING: 'warning',
    msg.ERROR: 'danger',
}

# ----------------------------------------------------------------------
# Configuraciones de Sesión
# ----------------------------------------------------------------------
SESSION_COOKIE_AGE = 60 * 60 * 2 
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_SECURE = False 
SESSION_COOKIE_SAMESITE = 'Lax'